### ISSUE TITLE
Notify giving me trouble

### ISSUE THREAD

**Issue by jeremycherfas** [Perlkonig/grav-plugin-webmention#2]
I installed the plugin on my [site](https://www.jeremycherfas.net/) and ran `notify` and `verify`.

Verify had nothing to do, because I had not received any webmentions. 

Notify sent out a bunch of links, but none of those was able to receive webmentions.

Then I created a post at [another site of mine](https://stream.jeremycherfas.net/2017/gorging-on-the-social-internet-jeremy-cherfas) which I hoped would send a web mention to my Grav site.

I also created a post on my Grav site linking to that post, hoping to have a web mention to send.

I ran notify and verify again, and both of them reported nothing to send and nothing to receive.

So I'm stumped. I need at least something in `receiver.file_data` to begin to start figuring out a template partial to display.

Would it matter that the site sending the web mention to the Grav site is in a subdomain of that site?

**Comment by Perlkonig** [comment]
So you ran notify on Site B and Site A didn't register the mention?

**Comment by jeremycherfas** [comment]
The subdomain thing was indeed not an issue. But I'm still trying to work out how best to troubleshoot. [Webmention.rocks says it is receiving a 404](https://webmention.rocks/receive/1/283f7342f565eb0b8826b4b47b0b69d4)

**Comment by jeremycherfas** [comment]
I've come back to this now, and very puzzled. Testing with https://telegraph.p3k.io/ [my Grav site](https://www.jeremycherfas.net/) does not return a status URL. However, looking in `data_received.yaml` I can see that the test webmention was indeed received.

I don't know whether this is anything you can fix, but it does make debugging quite difficult.

Thanks.

**Comment by Perlkonig** [comment]
Sorry for the delay. I need to be more responsive on GitHub. If you do a plain GET on the webmention receiver's endpoint, you should get this: https://www.perlkonig.com/mentions. But you're getting a 404?

**Comment by jeremycherfas** [comment]
No problem. I was getting a 404 from some of the webmention testers, but not when I go to that URL myself. It may be more an issue of the interaction between webmention.rocks and your plugin.
