### ISSUE TITLE
Should the webmention endpoint give a 404?

### ISSUE THREAD

**Issue by jeremycherfas** [Perlkonig/grav-plugin-webmention#3]
Other sites that implement webmention seem to have a visible webmention page, rather than a 404, [like this](https://stream.jeremycherfas.net/webmention/).

I suppose Grav would have to have a target page for that. Would it affect the workings of the plug-in?

**Comment by jeremycherfas** [comment]
I guess I can live with this until I understand better.

**Comment by Perlkonig** [comment]
You should be getting a 405 Method Not Allowed and a short message: https://www.perlkonig.com/mentions.
