### ISSUE TITLE
Plugin breaks RSS and Atom feeds

### ISSUE THREAD

**Issue by jeremycherfas** [Perlkonig/grav-plugin-webmention#5]
The placement of the webmention endpoint seems to break the Atom and RSS feeds. With the plugin active, those pages show

````
<link href="http://localhost:8888/mentions" rel="webmention" /><?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
    <title>Jeremy Cherfas: Posts</title>
````

And as a result (some?) feedreaders cannot access the feed. If the `rel="webmention"` line is not there (with the plugin disabled, all is well.

Looking at `webmention php` this (line 181) seems to be the place where the link is added

````
        $base = $this->grav['uri']->base();
        $rcvr_route = $config->get('plugins.webmention.receiver.route');
        $rcvr_url = $base.$rcvr_route;
        $tag = '<link href="'.$rcvr_url.'" rel="webmention" />'; 

        // inject before closing </head> tag
        $output = $this->grav->output;
        $output = substr_replace($output, $tag, strpos($output, '</head>'), 0); //inserts before closing HEAD tag

        // replace output
        $this->grav->output = $output;
````

I think the problem could be avoided by testing whether the page URI contains either "atom" or "RSS" but I can't seem to figure out how to get that.

OK, I think it available in `page.route` but no time to test now. More later.

**Comment by Perlkonig** [comment]
The latest release should have fixed this.
