### ISSUE TITLE
Wrong /route when developing locally 404 from endpoint

### ISSUE THREAD

**Issue by jeremycherfas** [Perlkonig/grav-plugin-webmention#7]
Hello. Me again, still trying to make this work so I can actually then work on displaying webmentions I receive.

I'm trying to develop locally, and there's a problem with the `/route` to the webmention endpoint.

The target specified in the source is `<link href="http://localhost:8888/mentions" rel="webmention" />`

I think it ought to be `<link href="http://localhost:8888/grav-admin/mentions" rel="webmention" />`

This may be something to do with the various flavours of Grav base URL. I'm checking further.

**Comment by Perlkonig** [comment]
You can set the receiver endpoint to whatever you want in the config `receiver: route:`. I can't imagine you'd want the admin plugin involved as that would require authentication. The receiver endpoint needs to be publicly accessible. Let me know if you have problems changing the route.

**Comment by jeremycherfas** [comment]
OK, thanks. Fixed as you suggested.
